### ISSUE TITLE
"Azure AI Language is not available" even though PIP packages are installed

### ISSUE THREAD

**Issue by whalygood** [microsoft/presidio#1460]
**Describe the bug**
For presidio-analyzer, "Azure AI Language is not available" even though PIP packages are installed

**To Reproduce**
1. Add the following to conf/default_recognizers.yaml

```
  - name: AzureAILanguageRecognizer
    supported_languages:
    - en
    type: predefined
    enabled: true
```

2. Add the following lines to the Dockerfile below `RUN pip install poetry && poetry install --no-root --only=main -E server`

```
RUN pip install azure-ai-textanalytics
RUN pip install azure-core
RUN pip install "presidio-analyzer[azure-ai-language]"
```

3. Build the container with the following command in presidio/presidio-analyzer
`docker build -t mcr.microsoft.com/presidio-analyzer . --no-cache`

4. Start the container with the AZURE_AI_KEY and AZURE_AI_ENDPOINT environment variables.

**Expected behavior**
Container to start (not crash) and load the Azure AI Language Recognizer properly.

**Additional context**
Here are the logs which the container crashes with upon start-up:

```
2024-10-03 14:53:22,881 - presidio-analyzer - INFO - Loaded recognizer: Azure AI Language PII
Traceback (most recent call last):
  File "/usr/bin/app.py", line 138, in <module>
    server = Server()
  File "/usr/bin/app.py", line 44, in __init__
    self.engine: AnalyzerEngine = AnalyzerEngineProvider(
  File "/usr/bin/presidio_analyzer/analyzer_engine_provider.py", line 79, in create_engine
    registry = self._load_recognizer_registry(
  File "/usr/bin/presidio_analyzer/analyzer_engine_provider.py", line 125, in _load_recognizer_registry
    registry = provider.create_recognizer_registry()
  File "/usr/bin/presidio_analyzer/recognizer_registry/recognizer_registry_provider.py", line 59, in create_recognizer_registry
    recognizers = RecognizerListLoader.get(
  File "/usr/bin/presidio_analyzer/recognizer_registry/recognizers_loader_utils.py", line 229, in get
    recognizer_instances.append(recognizer_cls(**kwargs))
  File "/usr/bin/presidio_analyzer/predefined_recognizers/azure_ai_language.py", line 55, in __init__
    raise ValueError(
ValueError: Azure AI Language is not available. Please install the required dependencies:1. azure-ai-textanalytics2. azure-core
2024-10-03 14:53:30,841 - presidio-analyzer - INFO - Starting analyzer engine
2024-10-03 14:53:30,841 - presidio-analyzer - INFO - Reading analyzer configuration from presidio_analyzer/conf/default_analyzer.yaml
2024-10-03 14:53:30,842 - presidio-analyzer - INFO - Reading nlp configuration from presidio_analyzer/conf/default.yaml
2024-10-03 14:53:32,050 - presidio-analyzer - INFO - Created NLP engine: spacy. Loaded models: ['en']
2024-10-03 14:53:32,050 - presidio-analyzer - INFO - Reading recognizer registry configuration from presidio_analyzer/conf/default_recognizers.yaml
2024-10-03 14:53:32,063 - presidio-analyzer - INFO - Loaded recognizer: Azure AI Language PII
Traceback (most recent call last):
  File "/usr/bin/app.py", line 138, in <module>
    server = Server()
  File "/usr/bin/app.py", line 44, in __init__
    self.engine: AnalyzerEngine = AnalyzerEngineProvider(
  File "/usr/bin/presidio_analyzer/analyzer_engine_provider.py", line 79, in create_engine
    registry = self._load_recognizer_registry(
  File "/usr/bin/presidio_analyzer/analyzer_engine_provider.py", line 125, in _load_recognizer_registry
    registry = provider.create_recognizer_registry()
  File "/usr/bin/presidio_analyzer/recognizer_registry/recognizer_registry_provider.py", line 59, in create_recognizer_registry
    recognizers = RecognizerListLoader.get(
  File "/usr/bin/presidio_analyzer/recognizer_registry/recognizers_loader_utils.py", line 229, in get
    recognizer_instances.append(recognizer_cls(**kwargs))
  File "/usr/bin/presidio_analyzer/predefined_recognizers/azure_ai_language.py", line 55, in __init__
    raise ValueError(
ValueError: Azure AI Language is not available. Please install the required dependencies:1. azure-ai-textanalytics2. azure-core
```

**Comment by whalygood** [comment]
The solution is to use the pyproject.toml and the poetry RUN command in the Dockerfile to install the dependencies instead. And also the config file for the recognizer registry cannot be bind mounted at run time, they must be built into the container. Will come back and close the issue if testing goes well. But the documentation should really be updated / improved.

**Comment by omri374** [comment]
Thanks @whalygood
