### ISSUE TITLE
ModuleNotFoundError: No module named 'protobuf_models'

### ISSUE THREAD

**Issue by jems25** [microsoft/presidio#320]
**Describe the bug**
Tried to install locally and ran the test program 

C:\Anaconda\python.exe "C:/Users/jesmi.harindran/Documents/Ticket Analysis Python/New folder/GSK.py"
Traceback (most recent call last):
  File "C:/Users/jesmi.harindran/Documents/Ticket Analysis Python/New folder/GSK.py", line 1, in <module>
    from presidio_analyzer import AnalyzerEngine
  File "C:\Anaconda\lib\site-packages\presidio_analyzer\__init__.py", line 17, in <module>
    from presidio_analyzer.analyzer_engine import AnalyzerEngine
  File "C:\Anaconda\lib\site-packages\presidio_analyzer\analyzer_engine.py", line 4, in <module>
    from protobuf_models import analyze_pb2
ModuleNotFoundError: No module named 'protobuf_models'

**To Reproduce**
followed the steps mentioned
Install presidio-analyzer as a Python package
f you're interested in running the analyzer alone, you can install it as a standalone python package by packaging it into a wheel file. Note that Presidio requires Python >= 3.6.

Creating the wheel file:
In the presidio-analyzer folder, run:

python setup.py bdist_wheel
Installing the wheel file
Copy the created wheel file (from the dist folder of presidio-analyzer) into a clean virtual environment

install wheel package

pip install wheel
Install the presidio-analyzer wheel file
pip install WHEEL_FILE
Where WHEEL_FILE is the path to the created wheel file

**Comment by omri374** [comment]
Hi @jems25, thanks for the information. We recently changed the way protobuf files are handled. We'll check if this introduced a bug and get back to you.

**Comment by ushurinterns-pragnyas** [comment]
The same issue persists when the package is installed via pip :
$pip install presidio-analyzer
Traceback (most recent call last):
  File "pii_pres.py", line 1, in <module>
    from presidio_analyzer import AnalyzerEngine
  File "C:\ProgramData\Anaconda3\lib\site-packages\presidio_analyzer\__init__.py", line 16, in <module>
    from presidio_analyzer.recognizer_registry.recognizer_registry \
  File "C:\ProgramData\Anaconda3\lib\site-packages\presidio_analyzer\recognizer_registry\__init__.py", line 2, in <module>
    from presidio_analyzer.recognizer_registry.recognizers_store_api import (  # noqa: F401, E501
  File "C:\ProgramData\Anaconda3\lib\site-packages\presidio_analyzer\recognizer_registry\recognizers_store_api.py", line 5, in <module>
    from protobuf_models import recognizers_store_pb2
ModuleNotFoundError: No module named 'protobuf_models'

**Comment by omri374** [comment]
Thank you @ushurinterns-pragnyas, this should be fixed in PR #321
