### ISSUE TITLE
presidio-analyzer docker image fails to start

### ISSUE THREAD

**Issue by akrock** [microsoft/presidio#355]
**Describe the bug**

Attempting to run the latest docker image results in a python Module error.

```
2020-08-03T02:36:53.781989647Z Traceback (most recent call last):
2020-08-03T02:36:53.78202595Z   File "app.py", line 15, in <module>
2020-08-03T02:36:53.782031594Z     from analyzer_engine import AnalyzerEngine  # noqa
2020-08-03T02:36:53.782035557Z   File "/usr/bin/presidio-analyzer/presidio_analyzer/analyzer_engine.py", line 4, in <module>
2020-08-03T02:36:53.782040406Z     from presidio_analyzer import PresidioLogger, RecognizerRegistry
2020-08-03T02:36:53.782043987Z ModuleNotFoundError: No module named 'presidio_analyzer'
```
**To Reproduce**
1. ` docker run  mcr.microsoft.com/presidio-analyzer:latest`

**Expected behavior**
Maybe an error about not being able to connect to the recognizer store? I'm not sure I have never seen it actually run.

**Additional context**
While I understand that this project is in a pre-production state and the latest builds might not always work, if the only builds that are made available are the latest builds, users would expect them to work. It might be helpful to make tags other than "latest" for known working release in the future?

**Comment by omri374** [comment]
Hi @akrock, thanks for the issue. This is probably an issue with the release pipeline not releasing the latest version. We're looking into this.

**Comment by omri374** [comment]
Released new version, issue is now fixed.
