### ISSUE TITLE
Documentation Build From Source Not reflective of steps.

### ISSUE THREAD

**Issue by jbullen94** [microsoft/presidio#760]
**Describe the bug**
When following the build from source steps. During the docker build you are faced with 
```
"RUN pipenv run python install_nlp_models.py --conf_file conf/default.yaml:
#29 3.271 Installing models from configuration: {'nlp_engine_name': 'spacy', 'models': [{'lang_code': 'en', 'model_name': 'en_core_web_sm'}]}
#29 3.356 Traceback (most recent call last):
#29 3.356   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
#29 3.359     httplib_response = self._make_request(
#29 3.359   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
#29 3.359     self._validate_conn(conn)
#29 3.359   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
#29 3.360     conn.connect()
#29 3.360   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
#29 3.361     self.sock = ssl_wrap_socket(
#29 3.361   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
#29 3.362     ssl_sock = _ssl_wrap_socket_impl(
#29 3.362   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
#29 3.363     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
#29 3.363   File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
#29 3.365     return self.sslsocket_class._create(
#29 3.365   File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
#29 3.366     self.do_handshake()
#29 3.366   File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
#29 3.368     self._sslobj.do_handshake()
#29 3.368 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
#29 3.368
#29 3.368 During handling of the above exception, another exception occurred:
#29 3.368
#29 3.368 Traceback (most recent call last):
#29 3.368   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
#29 3.369     resp = conn.urlopen(
#29 3.370   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
#29 3.371     retries = retries.increment(
#29 3.371   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
#29 3.373     raise MaxRetryError(_pool, url, error or ResponseError(cause))
#29 3.373 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
#29 3.373
#29 3.373 During handling of the above exception, another exception occurred:
#29 3.373
#29 3.374 Traceback (most recent call last):
#29 3.374   File "/usr/bin/presidio-analyzer/install_nlp_models.py", line 64, in <module>
#29 3.376     install_models(conf_file=args.conf_file)
#29 3.376   File "/usr/bin/presidio-analyzer/install_nlp_models.py", line 34, in install_models
#29 3.377     _download_model(engine_name, model_name)
#29 3.377   File "/usr/bin/presidio-analyzer/install_nlp_models.py", line 44, in _download_model
#29 3.377     spacy.cli.download(model_name)
#29 3.377   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/spacy/cli/download.py", line 67, in download
#29 3.378     compatibility = get_compatibility()
#29 3.378   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/spacy/cli/download.py", line 78, in get_compatibility
#29 3.378     r = requests.get(about.__compatibility__)
#29 3.378   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/api.py", line 76, in get
#29 3.379     return request('get', url, params=params, **kwargs)
#29 3.379   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
#29 3.379     return session.request(method=method, url=url, **kwargs)
#29 3.379   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
#29 3.381     resp = self.send(prep, **send_kwargs)
#29 3.381   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
#29 3.381     r = adapter.send(request, **kwargs)
#29 3.381   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
#29 3.382     raise SSLError(e, request=request)
#29 3.382 requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
```"


**To Reproduce**
Follow the steps verbatim for the "Build from Source" issue.

**Expected behavior**
When following the build from source there should be something within the section/dev setup section that denotes the requires to build an SSL ceritificate to be provided to the docker file.

**Comment by SharonHart** [comment]
Hi @jbullen94!
Can you please provide your OS and python version?
Try to install phthon certificates:
https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore
Alao verify that you're not behind a proxy or vpn

**Comment by jbullen94** [comment]
Looking at the analyzer only (purely for speed). I followed the steps in the above, I copied the PEM from certifi over to the build dir, made some tweaks to the docker file to copy over the crt into the ca share so the dockerfile now looks like this:

Running on Windows 10 Enterprise with Python 3.9 installed.

```

FROM python:3.9-slim

ARG NAME
ARG NLP_CONF_FILE=conf/default.yaml
ENV PIPENV_VENV_IN_PROJECT=1
WORKDIR /usr/bin/${NAME}

COPY ./Pipfile* /usr/bin/${NAME}/
COPY ./cacert.crt /usr/local/share/ca-certificates/cacert.crt
RUN update-ca-certificates

RUN pip install pipenv
RUN pipenv sync
# install nlp models specified in conf/default.yaml
COPY ./install_nlp_models.py /usr/bin/${NAME}/
COPY ${NLP_CONF_FILE} /usr/bin/${NAME}/${NLP_CONF_FILE}
RUN pipenv run python install_nlp_models.py --conf_file ${NLP_CONF_FILE}

COPY . /usr/bin/${NAME}/
EXPOSE ${PORT}
CMD pipenv run python app.py --host 0.0.0.0
```

Complete output of build from Docker... I can see that the cert is being copied over

```
docker-compose up --build -d
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"REGISTRY_NAME\" variable is not set. Defaulting to a blank string."
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"IMAGE_PREFIX\" variable is not set. Defaulting to a blank string."
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"TAG\" variable is not set. Defaulting to a blank string."
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"REGISTRY_NAME\" variable is not set. Defaulting to a blank string."
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"IMAGE_PREFIX\" variable is not set. Defaulting to a blank string."
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"TAG\" variable is not set. Defaulting to a blank string."
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"REGISTRY_NAME\" variable is not set. Defaulting to a blank string."
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"IMAGE_PREFIX\" variable is not set. Defaulting to a blank string."
time="2021-09-01T08:06:43+01:00" level=warning msg="The \"TAG\" variable is not set. Defaulting to a blank string."
[+] Building 14.3s (33/39)
 => [presidio-anonymizer internal] load build definition from Dockerfile                                           0.0s
 => => transferring dockerfile: 281B                                                                               0.0s
 => [presidio-image-redactor internal] load build definition from Dockerfile                                       0.0s
 => => transferring dockerfile: 417B                                                                               0.0s
 => [presidio-analyzer internal] load build definition from Dockerfile                                             0.0s
 => => transferring dockerfile: 656B                                                                               0.0s
 => [presidio-anonymizer internal] load .dockerignore                                                              0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [presidio-analyzer internal] load .dockerignore                                                                0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [presidio-image-redactor internal] load .dockerignore                                                          0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [presidio-analyzer internal] load metadata for docker.io/library/python:3.9-slim                              10.8s
 => [presidio-image-redactor internal] load metadata for docker.io/library/python:3.8-slim                        11.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [presidio-analyzer 1/6] FROM docker.io/library/python:3.9-slim@sha256:8402d0ea6e4eaeba7b390dfe522496e365334da  0.0s
 => [presidio-anonymizer internal] load build context                                                              0.1s
 => => transferring context: 153.19kB                                                                              0.1s
 => [presidio-analyzer internal] load build context                                                                0.2s
 => => transferring context: 577.39kB                                                                              0.2s
 => CACHED [presidio-anonymizer 2/6] WORKDIR /usr/bin/presidio-anonymizer                                          0.0s
 => CACHED [presidio-anonymizer 3/6] COPY ./Pipfile* /usr/bin/presidio-anonymizer/                                 0.0s
 => CACHED [presidio-anonymizer 4/6] RUN pip install pipenv                                                        0.0s
 => CACHED [presidio-anonymizer 5/6] RUN pipenv sync                                                               0.0s
 => [presidio-anonymizer 6/6] COPY . /usr/bin/presidio-anonymizer/                                                 0.1s
 => [presidio-image-redactor  1/10] FROM docker.io/library/python:3.8-slim@sha256:0762adcb498f2a6254ce1115a4f4b9a  0.0s
 => [presidio-image-redactor internal] load build context                                                          0.0s
 => => transferring context: 2.23kB                                                                                0.0s
 => CACHED [presidio-analyzer  2/11] WORKDIR /usr/bin/presidio-analyzer                                            0.0s
 => CACHED [presidio-analyzer  3/11] COPY ./Pipfile* /usr/bin/presidio-analyzer/                                   0.0s
 => [presidio-analyzer  4/11] COPY ./cacert.crt /usr/local/share/ca-certificates/cacert.crt                        0.1s
 => CACHED [presidio-image-redactor  2/10] WORKDIR /usr/bin/presidio-image-redactor                                0.0s
 => CACHED [presidio-image-redactor  3/10] RUN apt-get update                                                      0.0s
 => CACHED [presidio-image-redactor  4/10] RUN apt-get install tesseract-ocr -y                                    0.0s
 => CACHED [presidio-image-redactor  5/10] RUN tesseract -v                                                        0.0s
 => CACHED [presidio-image-redactor  6/10] COPY ./Pipfile* /usr/bin/presidio-image-redactor/                       0.0s
 => CACHED [presidio-image-redactor  7/10] RUN pip install pipenv                                                  0.0s
 => CACHED [presidio-image-redactor  8/10] RUN pipenv sync                                                         0.0s
 => ERROR [presidio-image-redactor  9/10] RUN pipenv run python -m spacy download en_core_web_lg                   2.7s
 => [presidio-anonymizer] exporting to image                                                                       0.1s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:872cb445d14223d8636f623de51ca32597ae6dd398247c0bdf165edbf72709cd                       0.0s
 => => naming to docker.io/library/presidio-anonymizer                                                             0.0s
 => [presidio-analyzer  5/11] RUN update-ca-certificates                                                           1.3s
 => CANCELED [presidio-analyzer  6/11] RUN pip install pipenv                                                      1.5s
------
 > [presidio-image-redactor  9/10] RUN pipenv run python -m spacy download en_core_web_lg:
#37 2.607 Traceback (most recent call last):
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
#37 2.607     httplib_response = self._make_request(
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
#37 2.607     self._validate_conn(conn)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
#37 2.607     conn.connect()
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
#37 2.607     self.sock = ssl_wrap_socket(
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
#37 2.607     ssl_sock = _ssl_wrap_socket_impl(
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
#37 2.607     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
#37 2.607   File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
#37 2.607     return self.sslsocket_class._create(
#37 2.607   File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
#37 2.607     self.do_handshake()
#37 2.607   File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
#37 2.607     self._sslobj.do_handshake()
#37 2.607 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)
#37 2.607
#37 2.607 During handling of the above exception, another exception occurred:
#37 2.607
#37 2.607 Traceback (most recent call last):
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
#37 2.607     resp = conn.urlopen(
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
#37 2.607     retries = retries.increment(
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
#37 2.607     raise MaxRetryError(_pool, url, error or ResponseError(cause))
#37 2.607 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
#37 2.607
#37 2.607 During handling of the above exception, another exception occurred:
#37 2.607
#37 2.607 Traceback (most recent call last):
#37 2.607   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
#37 2.607     return _run_code(code, main_globals, None,
#37 2.607   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
#37 2.607     exec(code, run_globals)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
#37 2.607     setup_cli()
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/spacy/cli/_util.py", line 69, in setup_cli
#37 2.607     command(prog_name=COMMAND)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
#37 2.607     return self.main(*args, **kwargs)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
#37 2.607     rv = self.invoke(ctx)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
#37 2.607     return _process_result(sub_ctx.command.invoke(sub_ctx))
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
#37 2.607     return ctx.invoke(self.callback, **ctx.params)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke#37 2.607     return callback(*args, **kwargs)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
#37 2.607     return callback(**use_params)  # type: ignore
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/spacy/cli/download.py", line 35, in download_cli
#37 2.607     download(model, direct, sdist, *ctx.args)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/spacy/cli/download.py", line 67, in download
#37 2.607     compatibility = get_compatibility()
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/spacy/cli/download.py", line 78, in get_compatibility
#37 2.607     r = requests.get(about.__compatibility__)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/requests/api.py", line 76, in get
#37 2.607     return request('get', url, params=params, **kwargs)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
#37 2.607     return session.request(method=method, url=url, **kwargs)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
#37 2.607     resp = self.send(prep, **send_kwargs)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
#37 2.607     r = adapter.send(request, **kwargs)
#37 2.607   File "/usr/bin/presidio-image-redactor/.venv/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
#37 2.607     raise SSLError(e, request=request)
#37 2.607 requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pipenv run python -m spacy download en_core_web_lg]: exit code: 1
```

**Comment by omri374** [comment]
Related to https://github.com/explosion/spaCy/issues/4297?

**Comment by SharonHart** [comment]
@jbullen94 Taking a look at the new logs youv'e provided, I think that the failure now is when bullding presidio-image-redactor, it is downloading a spacy model as well (actually a different one, if you compare to the first trace you've provided). Try to build just analyzer with compose so we can see if the certificates helped

**Comment by jbullen94** [comment]
I've run solely the analyzer. (I modified the docker-compose file) and this was the result. It looks like the issue lays with the spacy library?

```
docker-compose up --build -d
[+] Building 9.8s (15/16)
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                 4.1s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [ 1/11] FROM docker.io/library/python:3.9-slim@sha256:8402d0ea6e4eaeba7b390dfe522496e365334daaeb05361b24636f2  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 6.08kB                                                                                0.1s
 => CACHED [ 2/11] WORKDIR /usr/bin/presidio-analyzer                                                              0.0s
 => CACHED [ 3/11] COPY ./Pipfile* /usr/bin/presidio-analyzer/                                                     0.0s
 => CACHED [ 4/11] COPY ./cacert.crt /usr/local/share/ca-certificates/cacert.crt                                   0.0s
 => CACHED [ 5/11] RUN pip install pipenv                                                                          0.0s
 => CACHED [ 6/11] RUN pipenv sync                                                                                 0.0s
 => CACHED [ 7/11] RUN update-ca-certificates                                                                      0.0s
 => CACHED [ 8/11] COPY ./install_nlp_models.py /usr/bin/presidio-analyzer/                                        0.0s
 => CACHED [ 9/11] COPY conf/default.yaml /usr/bin/presidio-analyzer/conf/default.yaml                             0.0s
 => ERROR [10/11] RUN pipenv run python install_nlp_models.py --conf_file conf/default.yaml                        5.3s
------
 > [10/11] RUN pipenv run python install_nlp_models.py --conf_file conf/default.yaml:
#15 4.978 Installing models from configuration: {'nlp_engine_name': 'spacy', 'models': [{'lang_code': 'en', 'model_name': 'en_core_web_lg'}]}
#15 5.057 Traceback (most recent call last):
#15 5.057   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
#15 5.061     httplib_response = self._make_request(
#15 5.061   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
#15 5.062     self._validate_conn(conn)
#15 5.062   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
#15 5.063     conn.connect()
#15 5.063   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
#15 5.065     self.sock = ssl_wrap_socket(
#15 5.065   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
#15 5.067     ssl_sock = _ssl_wrap_socket_impl(
#15 5.068   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
#15 5.069     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
#15 5.069   File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
#15 5.070     return self.sslsocket_class._create(
#15 5.070   File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
#15 5.071     self.do_handshake()
#15 5.071   File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
#15 5.072     self._sslobj.do_handshake()
#15 5.072 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
#15 5.072
#15 5.072 During handling of the above exception, another exception occurred:
#15 5.072
#15 5.072 Traceback (most recent call last):
#15 5.072   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
#15 5.077     resp = conn.urlopen(
#15 5.078   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
#15 5.079     retries = retries.increment(
#15 5.079   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
#15 5.080     raise MaxRetryError(_pool, url, error or ResponseError(cause))
#15 5.080 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
#15 5.080
#15 5.080 During handling of the above exception, another exception occurred:
#15 5.080
#15 5.080 Traceback (most recent call last):
#15 5.080   File "/usr/bin/presidio-analyzer/install_nlp_models.py", line 64, in <module>
#15 5.081     install_models(conf_file=args.conf_file)
#15 5.081   File "/usr/bin/presidio-analyzer/install_nlp_models.py", line 34, in install_models
#15 5.082     _download_model(engine_name, model_name)
#15 5.082   File "/usr/bin/presidio-analyzer/install_nlp_models.py", line 44, in _download_model
#15 5.082     spacy.cli.download(model_name)
#15 5.082   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/spacy/cli/download.py", line 67, in download
#15 5.083     compatibility = get_compatibility()
#15 5.083   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/spacy/cli/download.py", line 78, in get_compatibility
#15 5.084     r = requests.get(about.__compatibility__)
#15 5.084   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/api.py", line 76, in get
#15 5.085     return request('get', url, params=params, **kwargs)
#15 5.085   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
#15 5.085     return session.request(method=method, url=url, **kwargs)
#15 5.085   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
#15 5.086     resp = self.send(prep, **send_kwargs)
#15 5.086   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
#15 5.087     r = adapter.send(request, **kwargs)
#15 5.087   File "/usr/bin/presidio-analyzer/.venv/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
#15 5.087     raise SSLError(e, request=request)
#15 5.087 requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pipenv run python install_nlp_models.py --conf_file ${NLP_CONF_FILE}]: exit code: 1
```

**Comment by SharonHart** [comment]
@jbullen94 Thanks for the investigation! In that case I'll close the issue, but will be happy if you'll post here how was it solved, for the sake of others with the same issue.

**Comment by omri374** [comment]
@jbullen94 You can perhaps try to download the spacy model straight from github, instead of using 'python -m spacy download...'

**Comment by jbullen94** [comment]
Issue persists within the docker image. I found a couple of links of the Spacy github that refer to them changing libraries to reduce dependencies.

**Comment by SharonHart** [comment]
I found a few options that could help:
First is to add a direct flag to the spacy download command: `python -m spacy download en_core_web_sm --direct`
Second is to use wget or curl to download it manually (maybe disable ssl verification for insecure download) and install using pip `python -m pip install en_core_web_sm-3.0.0.tar.gz`
